import type { PlantData } from './types';

export const samplePlants: PlantData[] = [
  {
    id: 'sample-1',
    latinName: 'Acer saccharum',
    commonName: 'Zucker-Ahorn',
    heightM: 25,
    widthM: 15,
    eatableScore: 2,
    medsScore: 1,
    materialScore: 4,
    eatable: true,
    culinaric: true,
    meds: true,
    material: true,
    fodder: false,
    fuel: true,
    nitrogenFix: false,
    mineralFix: false,
    groundCover: false,
    insects: true,
    pest: false,
    animalProtection: true,
    windBreaking: true,
    windBreakingOnSea: false,
    sunFull: true,
    sunMid: true,
    sunShadow: false,
    waterDry: false,
    waterMid: true,
    waterWet: false,
    phVeryAcid: false,
    phAcid: true,
    phNeutral: true,
    phAlkaline: false,
    phVeryAlkaline: false,
    growSpeedLow: false,
    growSpeedMid: true,
    growSpeedHigh: false,
    climateZone: '3-8',
    fruitMonths: [false,false,false,false,false,false,false,false,true,true,false,false],
    flowerMonths: [false,false,false,true,true,false,false,false,false,false,false,false],
    imageUrl: '',
  },
  {
    id: 'sample-2',
    latinName: 'Symphytum officinale',
    commonName: 'Beinwell',
    heightM: 1.2,
    widthM: 0.6,
    eatableScore: 2,
    medsScore: 4,
    materialScore: 3,
    eatable: true,
    culinaric: false,
    meds: true,
    material: true,
    fodder: true,
    fuel: false,
    nitrogenFix: false,
    mineralFix: true,
    groundCover: true,
    insects: true,
    pest: false,
    animalProtection: false,
    windBreaking: false,
    windBreakingOnSea: false,
    sunFull: true,
    sunMid: true,
    sunShadow: true,
    waterDry: false,
    waterMid: true,
    waterWet: true,
    phVeryAcid: false,
    phAcid: false,
    phNeutral: true,
    phAlkaline: true,
    phVeryAlkaline: false,
    growSpeedLow: false,
    growSpeedMid: false,
    growSpeedHigh: true,
    climateZone: '4-9',
    fruitMonths: [false,false,false,false,false,false,true,true,true,false,false,false],
    flowerMonths: [false,false,false,false,true,true,true,false,false,false,false,false],
    imageUrl: '',
  },
];
